#!/usr/bin/env python3
"""Build triage-data.js from analysis outputs for the HTML dashboard.

Also appends a metrics snapshot row to triage-log.csv for weekly tracking.
"""

import csv
import json
import time
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_FILE = BASE_DIR / "triage-data.js"
LOG_FILE = BASE_DIR / "triage-log.csv"
CLOSE_LOG_FILE = BASE_DIR / "close-log.csv"

LOG_HEADERS = [
    "date", "open", "stale", "frozen", "epics", "sprint",
    "orphaned", "duplicates",
]


def load_json(path):
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def append_log(metrics):
    """Append a metrics snapshot row to triage-log.csv.

    Skips if the last row has identical values (avoids duplicate entries
    from multiple runs on the same day with no changes).
    """
    file_exists = LOG_FILE.exists()
    if file_exists:
        with open(LOG_FILE) as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        if rows:
            last = rows[-1]
            # Compare all fields except date
            same = all(str(metrics.get(k, '')) == str(last.get(k, '')) for k in LOG_HEADERS if k != 'date')
            if same:
                print(f"Metrics unchanged, skipping log append.")
                return

    with open(LOG_FILE, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=LOG_HEADERS)
        if not file_exists:
            writer.writeheader()
        writer.writerow(metrics)
    print(f"Appended metrics to: {LOG_FILE}")


def load_previous_log():
    """Load the most recent log entry for delta calculation."""
    if not LOG_FILE.exists():
        return None
    with open(LOG_FILE) as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    return rows[-1] if rows else None


def load_close_log():
    """Load all closure records from close-log.csv."""
    if not CLOSE_LOG_FILE.exists():
        return []
    with open(CLOSE_LOG_FILE) as f:
        reader = csv.DictReader(f)
        return list(reader)


def load_metrics_log():
    """Load all metrics snapshots from triage-log.csv."""
    if not LOG_FILE.exists():
        return []
    with open(LOG_FILE) as f:
        reader = csv.DictReader(f)
        return list(reader)


def main():
    tickets_data = load_json(BASE_DIR / "tickets.json")
    duplicates = load_json(BASE_DIR / "duplicate_candidates.json")
    priorities = load_json(BASE_DIR / "priority_scores.json")

    all_tickets = tickets_data["tickets"] if tickets_data else []
    stale_tickets = tickets_data.get("stale_tickets", []) if tickets_data else []
    frozen_tickets = tickets_data.get("frozen_tickets", []) if tickets_data else []
    recently_closed = tickets_data.get("recently_closed", []) if tickets_data else []

    # Compute metrics
    epic_count = sum(1 for t in all_tickets if t.get("type") == "Epic")
    sprint_count = sum(1 for t in all_tickets if t.get("sprint") and t.get("type") != "Epic")
    orphaned_count = sum(1 for t in all_tickets if t.get("parent_status") in ("Closed", "Done"))
    dup_count = 0
    if duplicates:
        dup_count = duplicates.get("duplicate_pairs_found", 0)

    # Load previous for deltas
    prev = load_previous_log()
    deltas = None
    if prev:
        deltas = {}
        current = {
            "open": len(all_tickets), "stale": len(stale_tickets),
            "frozen": len(frozen_tickets), "orphaned": orphaned_count,
        }
        for k in current:
            prev_val = int(prev.get(k, 0))
            diff = current[k] - prev_val
            if diff != 0:
                deltas[k] = {"prev": prev_val, "current": current[k], "diff": diff}

    # Load history for the Triage History tab
    close_log = load_close_log()
    metrics_log = load_metrics_log()

    data = {
        "meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total_tickets": tickets_data["count"] if tickets_data else 0,
            "stale_count": len(stale_tickets),
            "frozen_count": len(frozen_tickets),
            "jql": tickets_data["jql"] if tickets_data else "",
            "deltas": deltas,
        },
        "duplicates": duplicates,
        "priorities": priorities,
        "tickets": all_tickets,
        "stale_tickets": stale_tickets,
        "frozen_tickets": frozen_tickets,
        "recently_closed": recently_closed,
        "close_log": close_log,
        "metrics_log": metrics_log,
    }

    js_content = (
        "// Backlog Triage Data — auto-generated by build_html_data.py\n"
        f"// Last updated: {data['meta']['generated_at']}\n"
        f"window.TRIAGE_DATA = {json.dumps(data, indent=None)};\n"
    )

    with open(OUTPUT_FILE, "w") as f:
        f.write(js_content)

    print(f"Written: {OUTPUT_FILE} ({len(js_content)} bytes)")

    # Append metrics to log
    metrics = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "open": len(all_tickets),
        "stale": len(stale_tickets),
        "frozen": len(frozen_tickets),
        "epics": epic_count,
        "sprint": sprint_count,
        "orphaned": orphaned_count,
        "duplicates": dup_count,
    }
    append_log(metrics)


if __name__ == "__main__":
    main()
