#!/usr/bin/env python3
"""Build triage-data.js from analysis outputs for the HTML dashboard."""

import json
import time
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_FILE = BASE_DIR / "triage-data.js"


def load_json(path):
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def main():
    tickets = load_json(BASE_DIR / "tickets.json")
    duplicates = load_json(BASE_DIR / "duplicate_candidates.json")
    obsolete = load_json(BASE_DIR / "obsolete_candidates.json")
    priorities = load_json(BASE_DIR / "priority_scores.json")

    data = {
        "meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "total_tickets": tickets["count"] if tickets else 0,
            "stale_count": tickets.get("stale_count", 0) if tickets else 0,
            "frozen_count": tickets.get("frozen_count", 0) if tickets else 0,
            "jql": tickets["jql"] if tickets else "",
        },
        "duplicates": duplicates,
        "obsolete": obsolete,
        "priorities": priorities,
        "tickets": tickets["tickets"] if tickets else [],
        "stale_tickets": tickets.get("stale_tickets", []) if tickets else [],
        "frozen_tickets": tickets.get("frozen_tickets", []) if tickets else [],
    }

    js_content = (
        "// Backlog Triage Data — auto-generated by build_html_data.py\n"
        f"// Last updated: {data['meta']['generated_at']}\n"
        f"window.TRIAGE_DATA = {json.dumps(data, indent=None)};\n"
    )

    with open(OUTPUT_FILE, "w") as f:
        f.write(js_content)

    print(f"Written: {OUTPUT_FILE} ({len(js_content)} bytes)")


if __name__ == "__main__":
    main()
