#!/usr/bin/env python3
"""Close Jira tickets from a triage manifest file.

Reads close-manifest.json (generated by the triage report UI) and for each ticket:
1. Adds the triage label (e.g. triage-closed-orphan)
2. Transitions to Closed with the specified resolution
3. Adds a comment explaining the closure reason

Usage:
    python3 scripts/close_tickets.py                    # dry-run (default)
    python3 scripts/close_tickets.py --execute          # actually close tickets
    python3 scripts/close_tickets.py --manifest path    # use a specific manifest file
"""

import argparse
import csv
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path

import requests

JIRA_INSTANCE = "redhat.atlassian.net"
BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = BASE_DIR / "close-manifest.json"
CLOSE_LOG_FILE = BASE_DIR / "close-log.csv"

TRANSITION_CLOSED = "51"

RESOLUTION_IDS = {
    "Done": "10000",
    "Won't Do": "10001",
    "Cannot Reproduce": "10003",
    "Can't Do": "10040",
    "Duplicate": "10002",
    "Not a Bug": "10037",
    "Done-Errata": "10041",
    "MirrorOrphan": "10042",
    "Obsolete": "10038",
    "Test Pending": "10039",
    "Declined": "10075",
}


def get_auth():
    email = os.environ.get("JIRA_EMAIL")
    token = os.environ.get("JIRA_TOKEN")
    if not email or not token:
        print("ERROR: JIRA_EMAIL and JIRA_TOKEN environment variables required", file=sys.stderr)
        sys.exit(1)
    return (email, token)


def get_ticket_status(key, auth):
    """Fetch the current status of a ticket. Returns (status_name, labels) or (None, [])."""
    url = f"https://{JIRA_INSTANCE}/rest/api/3/issue/{key}?fields=status,labels"
    resp = requests.get(url, auth=auth)
    if resp.status_code == 429:
        time.sleep(int(resp.headers.get("Retry-After", 5)))
        resp = requests.get(url, auth=auth)
    if resp.status_code != 200:
        return None, []
    data = resp.json()
    status = data.get("fields", {}).get("status", {}).get("name", "")
    labels = data.get("fields", {}).get("labels", [])
    return status, labels


def add_label(key, label, auth):
    """Add a triage-closed label and remove any prior triage-reverted label."""
    url = f"https://{JIRA_INSTANCE}/rest/api/3/issue/{key}"
    payload = {"update": {"labels": [{"add": label}, {"remove": "triage-reverted"}]}}
    resp = requests.put(url, json=payload, auth=auth)
    if resp.status_code == 429:
        time.sleep(int(resp.headers.get("Retry-After", 5)))
        resp = requests.put(url, json=payload, auth=auth)
    return resp.status_code == 204


def transition_to_closed(key, resolution_name, auth):
    """Transition a ticket to Closed with specified resolution.
    Falls back to transition without resolution if the workflow screen
    doesn't support the resolution field."""
    url = f"https://{JIRA_INSTANCE}/rest/api/3/issue/{key}/transitions"
    resolution_id = RESOLUTION_IDS.get(resolution_name)
    if not resolution_id:
        print(f"  ERROR: Unknown resolution '{resolution_name}'", file=sys.stderr)
        return False

    payload = {
        "transition": {"id": TRANSITION_CLOSED},
        "fields": {
            "resolution": {"id": resolution_id}
        }
    }
    resp = requests.post(url, json=payload, auth=auth)
    if resp.status_code == 429:
        time.sleep(int(resp.headers.get("Retry-After", 5)))
        resp = requests.post(url, json=payload, auth=auth)

    if resp.status_code == 400 and "resolution" in resp.text:
        payload_no_res = {"transition": {"id": TRANSITION_CLOSED}}
        resp = requests.post(url, json=payload_no_res, auth=auth)
        if resp.status_code == 204:
            print("(no-resolution fallback)", end=" ")
            return True

    if resp.status_code != 204:
        print(f"  ERROR transitioning {key}: {resp.status_code} {resp.text[:200]}", file=sys.stderr)
        return False
    return True


def add_comment(key, reason, auth):
    """Add a comment to the ticket explaining the closure."""
    url = f"https://{JIRA_INSTANCE}/rest/api/3/issue/{key}/comment"
    comment_text = f"Closed via backlog triage — reason: {reason}"
    payload = {
        "body": {
            "type": "doc",
            "version": 1,
            "content": [{
                "type": "paragraph",
                "content": [{"type": "text", "text": comment_text}]
            }]
        }
    }
    resp = requests.post(url, json=payload, auth=auth)
    if resp.status_code == 429:
        time.sleep(int(resp.headers.get("Retry-After", 5)))
        resp = requests.post(url, json=payload, auth=auth)
    return resp.status_code == 201


def log_closures(items):
    """Append closure records to close-log.csv."""
    file_exists = CLOSE_LOG_FILE.exists()
    with open(CLOSE_LOG_FILE, "a", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["date", "key", "summary", "resolution", "label", "reason"])
        date = datetime.now().strftime("%Y-%m-%d")
        for item in items:
            writer.writerow([date, item["key"], item.get("summary", ""), item["resolution"], item["label"], item["reason"]])


def main():
    parser = argparse.ArgumentParser(description="Close Jira tickets from triage manifest")
    parser.add_argument("--execute", action="store_true", help="Actually close tickets (default is dry-run)")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Path to close-manifest.json")
    parser.add_argument("--stdin", action="store_true", help="Read manifest JSON from stdin")
    args = parser.parse_args()

    if args.stdin:
        manifest = json.load(sys.stdin)
    elif args.manifest.exists():
        manifest = json.loads(args.manifest.read_text())
    else:
        print(f"ERROR: Manifest not found: {args.manifest}", file=sys.stderr)
        print("Generate one from the triage report UI (triple-click to unlock close mode).", file=sys.stderr)
        sys.exit(1)
    items = manifest.get("items", [])

    if not items:
        print("No items in manifest. Nothing to do.")
        return

    print(f"{'DRY RUN' if not args.execute else 'EXECUTING'} — {len(items)} tickets to close")
    print(f"Manifest generated: {manifest.get('generated_at', 'unknown')}")
    print()

    by_category = {}
    for item in items:
        cat = item.get("label", "unknown").replace("triage-closed-", "")
        by_category.setdefault(cat, []).append(item)

    for cat, cat_items in by_category.items():
        print(f"  {cat}: {len(cat_items)} tickets (resolution: {cat_items[0]['resolution']})")
    print()

    if not args.execute:
        print("Items to close:")
        for item in items:
            print(f"  {item['key']:12s} | {item['resolution']:12s} | {item['label']} | {item['reason']}")
        print()
        print("Run with --execute to actually close these tickets.")
        return

    auth = get_auth()
    success = 0
    failed = 0
    skipped = 0
    closed_items = []

    for i, item in enumerate(items, 1):
        key = item["key"]
        resolution = item["resolution"]
        label = item["label"]
        reason = item["reason"]

        print(f"[{i}/{len(items)}] {key} → {resolution}...", end=" ")

        status, labels = get_ticket_status(key, auth)
        if status and status.lower() in ("closed", "done"):
            if label not in labels:
                add_label(key, label, auth)
            print(f"SKIPPED (already {status})")
            skipped += 1
            continue

        ok_label = add_label(key, label, auth)
        if not ok_label:
            print("WARN: label failed, continuing...")

        ok_transition = transition_to_closed(key, resolution, auth)
        if not ok_transition:
            print("FAILED")
            failed += 1
            continue

        add_comment(key, reason, auth)
        print("OK")
        success += 1
        closed_items.append(item)
        time.sleep(0.3)

    skip_msg = f", {skipped} skipped" if skipped else ""
    print(f"\nDone: {success} closed, {failed} failed{skip_msg}")

    if closed_items:
        log_closures(closed_items)
        print(f"Logged to: {CLOSE_LOG_FILE}")


if __name__ == "__main__":
    main()
